config/routes.rb
RbacClient::Application.routes.draw do

  root :to => 'home#index'

  match 'home/index' => 'home#index', :as => 'home'

  resources :things

  get '/roles' => 'GciRbac::Roles#index',
      :as => 'roles'
  get '/roles/:role_name' => 'GciRbac::Roles#show',
      :as => 'role'
  get '/roles/:role_name/edit' => 'GciRbac::Roles#edit',
      :as => 'edit_role'
  put '/roles/:role_name' => 'GciRbac::Roles#update',
      :as => 'update_role' 
 

  match '/login' => 'GciRbac::Login#login', :as => 'login'
  match '/logout' => 'GciRbac::Login#logout', :as => 'logout'

end

app/models/thing.rb
class Thing < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < GciRbac::AuthorizationController
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/things_controller.rb
class ThingsController < ApplicationController
  require_authority 'View Thing'

  # GET /things
  # GET /things.xml
  def index
    @things = Thing.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @things }
    end
  end

  # GET /things/1
  # GET /things/1.xml
  def show
    @thing = Thing.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @thing }
    end
  end

  # GET /things/new
  # GET /things/new.xml
  def new
    @thing = Thing.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @thing }
    end
  end

  # GET /things/1/edit
  def edit
    @thing = Thing.find(params[:id])
  end

  # POST /things
  # POST /things.xml
  def create
    @thing = Thing.new(params[:thing])

    respond_to do |format|
      if @thing.save
        format.html { redirect_to(@thing, :notice => 'Thing was successfully created.') }
        format.xml  { render :xml => @thing, :status => :created, :location => @thing }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @thing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /things/1
  # PUT /things/1.xml
  def update
    @thing = Thing.find(params[:id])

    respond_to do |format|
      if @thing.update_attributes(params[:thing])
        format.html { redirect_to(@thing, :notice => 'Thing was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @thing.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /things/1
  # DELETE /things/1.xml
  def destroy
    @thing = Thing.find(params[:id])
    @thing.destroy

    respond_to do |format|
      format.html { redirect_to(things_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>

<p>Session data:<pre><%= session.inspect %></pre></p>

app/views/layouts/_header.html.erb
<div class="header">
  <div class="app_banner">
    <%= link_to "#{request.host} - Rbac Client", root_path %>
    <% if not session[:user_id].blank? %>
      <%= button_to "Logout #{session[:user_id]}", logout_path,
                    :method => :get %>
    <% end %>
  </div>
  <% if not session[:user_id].blank? %>
    <div class="nav">
      <ul>
          <%= render :partial => 'layouts/tab', :object => 'roles' %>
          <%= render :partial => 'layouts/tab', :object => 'things' %>
      </ul>
    </div>
  <% end %>
</div>

app/views/layouts/_tab.html.erb
<% if request.parameters['controller'] =~ Regexp.new(tab, Regexp::IGNORECASE) or
      request.parameters['action'] == tab -%>
  <li class="current"><%= tab.capitalize %></li>
<% else -%>
  <li><%= link_to tab.capitalize, send(tab + '_path') %></li>
<% end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rbac Client</title>
    <%= stylesheet_link_tag 'base' %>
    <!--[if IE]>
      <%= stylesheet_link_tag 'iebase' %>
    <![endif]-->
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="content">
      <% if notice %><p id="notice"><%= notice %></p><% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/things/_form.html.erb
<%= form_for(@thing) do |f| %>
  <% if @thing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@thing.errors.count, "error") %> prohibited this thing from being saved:</h2>

      <ul>
      <% @thing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/things/edit.html.erb
<h1>Editing thing</h1>

<%= render 'form' %>

<%= link_to 'Show', @thing %> |
<%= link_to 'Back', things_path %>

app/views/things/index.html.erb
<h1>Listing things</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Value</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @things.each do |thing| %>
  <tr>
    <td><%= thing.name %></td>
    <td><%= thing.value %></td>
    <td><%= link_to 'Show', thing %></td>
    <td><%= link_to 'Edit', edit_thing_path(thing) %></td>
    <td><%= link_to 'Destroy', thing, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Thing', new_thing_path %>

app/views/things/new.html.erb
<h1>New thing</h1>

<%= render 'form' %>

<%= link_to 'Back', things_path %>

app/views/things/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @thing.name %>
</p>

<p>
  <b>Value:</b>
  <%= @thing.value %>
</p>


<%= link_to 'Edit', edit_thing_path(@thing) %> |
<%= link_to 'Back', things_path %>